name: Release

on:
  push:
    tags: ['v**']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
    - uses: actions/checkout@v4
    - name: Build Release Artifact
      run: cargo build --release
    - name: Attest
      id: attest
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: "${{ github.workspace }}/target/release/dough"
    - name: Package Release
      id: package
      run: |
        mkdir release
        cp target/release/dough release
        cp README.md release
        cp LICENSE.md release
        cp "${{ steps.attest.outputs.bundle-path }}" release
        tar -C release -czvf "dough-${GITHUB_REF_NAME}-linux-$(uname -m).tar.gz" .
        echo "output-file=dough-${GITHUB_REF_NAME}-linux-$(uname -m).tar.gz" >> "$GITHUB_OUTPUT"
    - name: Make Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: ${{ steps.package.outputs.output-file }}
