name: Rust

on:
  push:
    branches: ['**']
    paths:
      - .github/workflows/rust.yml
      - '**/*.rs'
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

